name: Smart ML Pipeline

on:
  push:
    branches:
      - "*"

jobs:

  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Linter
        run: |
          pip install flake8
          flake8 .

  train:
    needs: linter
    runs-on: ubuntu-latest

    if: >
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, '[run-train]')

    steps:
      - uses: actions/checkout@v4

      - name: Run Training
        run: echo "Training model..."
