name: Model Training and Deployment Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Linter
        run: echo "Running lint checks..."


  train:
    needs: linter 
    if: |
      github.ref == 'refs/heads/main' && 
      contains(github.event.head_commit.message, '[run-train]')
 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      
      - name: Training Model
        run: |
          echo "Training starting..."
      
          # exit 1 
          echo "Training finished successfully."

      
      - name: Upload Error Logs
        if: failure() # تعمل فقط عند فشل الـ train
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: error_logs.txt


  cleanup:
    needs: [linter, train]
    if: always() 
    runs-on: ubuntu-latest
    steps:
      - name: Final Cleanup
        run: echo "Cleaning up temporary cloud volumes..."
